package com.tourify.tourifyapp.constants

object Constants {
    const val PATH_LOGIN = "checkEmail"
    const val PREFS_LOGIN = "loginPreference"
    const val PREFS_ONBOARDING = "onBoardingPreference"
    const val CATEGORY_ADVENTURE = "Pertualangan"
    const val CATEGORY_FAMILY_VACATION = "Liburan Keluarga"
    const val CATEGORY_HONEYMOON = "Bulan Madu"
    const val CATEGORY_EDUCATION_CULTURE = "Pendidikan & Budaya"
    const val CATEGORY_PHOTOGRAPHY_VIDEOGRAPHY = "Fotografi & Videografi"
    const val CATEGORY_RECREATION = "Rekreasi"
    const val CATEGORY_ICONIC_SIGHT = "Pemandangan Ikonis"
    const val START_DATE = "Start Date"
    const val END_DATE = "End Date"

    const val ACEH = "Aceh"
    const val NORTH_SUMATRA = "Sumatra Utara"
    const val WEST_SUMATRA = "Sumatra Barat"
    const val RIAU = "Riau"
    const val RIAU_ISLANDS = "Kepulauan Riau"
    const val JAMBI = "Jambi"
    const val SOUTH_SUMATRA = "Sumatera Selatan"
    const val BANGKA_BELITUNG = "Bangka Belitung"
    const val BENGKULU = "Bengkulu"
    const val LAMPUNG = "Lampung"
    const val BANTEN = "Banten"
    const val WEST_JAVA = "Jawa Barat"
    const val JAKARTA = "DKI Jakarta"
    const val CENTRAL_JAVA = "Jawa Tengah"
    const val YOGYAKARTA = "D. I. Yogyakarta"
    const val EAST_JAVA = "Jawa Timur"
    const val BALI = "Bali"
    const val WEST_NUSA_TENGGARA = "NTB"
    const val EAST_NUSA_TENGGARA = "NTT"
    const val WEST_KALIMANTAN = "Kalimantan Barat"
    const val CENTRAL_KALIMANTAN = "Kalimantan Tengah"
    const val SOUTH_KALIMANTAN = "Kalimantan Selatan"
    const val EAST_KALIMANTAN = "Kalimantan Timur"
    const val NORTH_KALIMANTAN = "Kalimantan Utara"
    const val NORTH_SULAWESI = "Sulawesi Utara"
    const val CENTRAL_SULAWESI = "Sulawesi Tengah"
    const val SOUTH_SULAWESI = "Sulawesi Selatan"
    const val SOUTHEAST_SULAWESI = "Sulawesi Tenggara"
    const val GORONTALO = "Gorontalo"
    const val WEST_SULAWESI = "Sulawesi Barat"
    const val MALUKU = "Maluku"
    const val NORTH_MALUKU = "Maluku Utara"
    const val PAPUA = "Papua"
}